  steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['install']
  - name: gcr.io/sonar-scanner:latest
    args:
        - '-Dsonar.host.url=https://sonarcloud.io'
        - '-Dsonar.login=0e2f403439bc383b660fe884516cb1ef0116c5a0'
        - '-Dsonar.projectKey=ashwani77_java-maven-calculator-web-app'
        - '-Dsonar.sources=.'
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/calculator", "--build-arg=WAR_FILE=target/calculator.war", "."]
  images: ["gcr.io/$PROJECT_ID/calculator"]